name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
        Before we start, be sure you are aware of the following points:
        
        * If your issue is specific to a certain plugin, create the issue on that plugin's GitHub project page instead.
        * Avoid duplicating any existing issues which already track or resolve your problem, search the existing issues first.
        * Aim to find a descriptive and precise title for your bug report.
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe The Bug
      description: |
        Pleased provide a clear and concise description of what the bug is. Be sure to include:
        
        * What is happening?
        * What you expect to happen?
        * Clear steps explaining how to reproduce the problem.
      placeholder: |
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: true
  - type: textarea
    id: docker-config
    attributes:
      label: Docker Config
      render: yml
      description: |
        Please include your `docker run ...` command or `docker-compose.yml` file.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: text
      description: |
        Please provide the relevant logs showing the error that occurred.

        * Keep this short. Do not paste in hundereds of lines repeating the same error.
        * Show the logs from the service being restarted until the error is occurs.
    validations:
      required: false
  - type: dropdown
    id: operating-system
    attributes:
      label: Host Operating System
      options:
        - Raspberry Pi OS / Raspbian
        - Ubuntu / Debian (or a variant)
        - Fedora / CentOS / RedHat (or a variant)
        - Synology DSM
        - QNAP
        - Unraid
        - Other (specify in description)
      description: |
        If your operating system is not listed, please provide it in the bug description.

        **Please note that macOS and Windows are not supported as host operating systems. [See this for more info](https://github.com/oznu/docker-homebridge#compatibility).**
    validations:
      required: true
